# Generated by Django 3.1.2 on 2020-10-23 07:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apis', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gallery',
            name='artist',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
    ]
