# Generated by Django 3.1.2 on 2020-11-02 05:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apis', '0006_auto_20201030_1553'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='email',
            field=models.TextField(default='tom@gmail.com'),
            preserve_default=False,
        ),
    ]
