# Generated by Django 3.1.2 on 2020-11-02 05:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apis', '0007_message_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='email',
            field=models.CharField(max_length=100),
        ),
    ]
